### ISSUE TITLE
Crash when i tried adding a gif

### ISSUE THREAD

**Issue by ghost** [Nettakrim/Signed-Paintings#12]
crash log:
```
Description: Rendering Block Entity

java.lang.NullPointerException: Cannot invoke "org.joml.Matrix4f.m00()" because "mat" is null
	at net.caffeinemc.mods.sodium.api.math.MatrixHelper.transformPositionX(MatrixHelper.java:81)
	at net.minecraft.class_4588.method_22918(class_4588.java:526)
	at com.nettakrim.signed_paintings.rendering.Cuboid.vertex(Cuboid.java:122)
	at com.nettakrim.signed_paintings.rendering.Cuboid.vertexFromVector(Cuboid.java:118)
	at com.nettakrim.signed_paintings.rendering.Cuboid.renderQuad(Cuboid.java:111)
	at com.nettakrim.signed_paintings.rendering.Cuboid.renderFaceRotated(Cuboid.java:84)
	at com.nettakrim.signed_paintings.rendering.Cuboid.renderFace(Cuboid.java:70)
	at com.nettakrim.signed_paintings.rendering.PaintingRenderer.renderImage(PaintingRenderer.java:43)
	at com.nettakrim.signed_paintings.rendering.PaintingRenderer.renderPainting(PaintingRenderer.java:31)
	at net.minecraft.class_837.renderPaintingInfo(class_837.java:1549)
	at net.minecraft.class_837.signedPaintings$enhancedRender(class_837.java:1567)
	at foundationgames.enhancedblockentities.client.render.entity.SignBlockEntityRendererOverride.handler$oel000$signed_paintings$enhancedRender(SignBlockEntityRendererOverride.java:519)
	at foundationgames.enhancedblockentities.client.render.entity.SignBlockEntityRendererOverride.render(SignBlockEntityRendererOverride.java)
	at net.minecraft.class_824.handler$ffc000$enhancedblockentities$enhanced_bes$renderOverrides(class_824.java:530)
	at net.minecraft.class_824.method_23079(class_824.java)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:369)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:308)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:271)
	at net.minecraft.class_761.handler$onl000$sodium$onRenderBlockEntities(class_761.java:30599)
	at net.minecraft.class_761.method_22710(class_761.java:1372)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.caffeinemc.mods.sodium.api.math.MatrixHelper.transformPositionX(MatrixHelper.java:81)
	at net.minecraft.class_4588.method_22918(class_4588.java:526)
	at com.nettakrim.signed_paintings.rendering.Cuboid.vertex(Cuboid.java:122)
	at com.nettakrim.signed_paintings.rendering.Cuboid.vertexFromVector(Cuboid.java:118)
	at com.nettakrim.signed_paintings.rendering.Cuboid.renderQuad(Cuboid.java:111)
	at com.nettakrim.signed_paintings.rendering.Cuboid.renderFaceRotated(Cuboid.java:84)
	at com.nettakrim.signed_paintings.rendering.Cuboid.renderFace(Cuboid.java:70)
	at com.nettakrim.signed_paintings.rendering.PaintingRenderer.renderImage(PaintingRenderer.java:43)
	at com.nettakrim.signed_paintings.rendering.PaintingRenderer.renderPainting(PaintingRenderer.java:31)
	at net.minecraft.class_837.renderPaintingInfo(class_837.java:1549)
	at net.minecraft.class_837.signedPaintings$enhancedRender(class_837.java:1567)
	at foundationgames.enhancedblockentities.client.render.entity.SignBlockEntityRendererOverride.handler$oel000$signed_paintings$enhancedRender(SignBlockEntityRendererOverride.java:519)
	at foundationgames.enhancedblockentities.client.render.entity.SignBlockEntityRendererOverride.render(SignBlockEntityRendererOverride.java)
	at net.minecraft.class_824.handler$ffc000$enhancedblockentities$enhanced_bes$renderOverrides(class_824.java:530)
	at net.minecraft.class_824.method_23079(class_824.java)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:369)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:308)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:271)
	at net.minecraft.class_761.handler$onl000$sodium$onRenderBlockEntities(class_761.java:30599)
	at net.minecraft.class_761.method_22710(class_761.java:1372)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	```

**Comment by Nettakrim** [comment]
interesting, gifs don't work as it is but last I checked it just took the first frame instead of crashing, do you still have the exact link you used? to help reproduce the issue

**Comment by ghost** [comment]
Oh you're right, i should've included the link that it crashed with... unfortunately i lost it.

All i remember is that i googled "Cat dancing gif" 😐

**Comment by r1sk01** [comment]
> interesting, gifs don't work as it is but last I checked it just took the first frame instead of crashing, do you still have the exact link you used? to help reproduce the issue

this is still occurring, it breaks the rendering api  
gif: https://zeusteam.dev/favicon.ico

**Comment by r1sk01** [comment]
---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-11-13 18:58:22
Description: Rendering screen

java.lang.StringIndexOutOfBoundsException: begin 0, end 15, length 12
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
	at java.base/java.lang.String.substring(String.java:2709)
	at knot//net.minecraft.class_7743.method_45655(class_7743.java:212)
	at knot//net.minecraft.class_7743.method_45659(class_7743.java:153)
	at knot//net.minecraft.class_7743.method_25394(class_7743.java:112)
	at knot//net.minecraft.class_437.method_47413(class_437.java:110)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$280(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bel000$fabric-screen-api-v1$onRenderScreen(class_757.java:3111)
	at knot//net.minecraft.class_757.method_3192(class_757.java:931)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1327)
	at knot//net.minecraft.class_310.method_1514(class_310.java:888)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
	at java.base/java.lang.String.substring(String.java:2709)
	at knot//net.minecraft.class_7743.method_45655(class_7743.java:212)
	at knot//net.minecraft.class_7743.method_45659(class_7743.java:153)
	at knot//net.minecraft.class_7743.method_25394(class_7743.java:112)
	at knot//net.minecraft.class_437.method_47413(class_437.java:110)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$280(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bel000$fabric-screen-api-v1$onRenderScreen(class_757.java:3111)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_498
	Mouse location: Scaled: (42, 96). Absolute: (84.000000, 192.000000)
	Screen size: Scaled: (960, 502). Absolute: (1920, 1004). Scale factor of 2.000000
Stacktrace:
	at knot//net.minecraft.class_757.method_3192(class_757.java:931)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1327)
	at knot//net.minecraft.class_310.method_1514(class_310.java:888)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Linux (amd64) version 6.11.6-arch1-1
	Java Version: 17.0.12, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 293827568 bytes (280 MiB) / 1333788672 bytes (1272 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: TigerLake-H GT1 [UHD Graphics]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x9a60
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 11961.77
	Virtual memory used (MB): 14297.43
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 2113.25
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		advancedbackups: Advanced Backups 3.6.3
		backported_wolves: Backported Wolves 1.1.0-1.19.3-1.20.4
		cloth-config: Cloth Config v13 13.0.138
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.64
		darkorb: DarkOrb - Orb of Origin Recipes 1.0.1
		fabric-api: Fabric API 0.97.2+1.20.4
			fabric-api-base: Fabric API Base 0.4.37+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.50+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.17+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.17+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.5+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.47+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.8+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.42+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.21+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.59+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.88+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.16+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.11+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.24+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.5+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.6+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.63+6605d1a84f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.2+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.2+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.75+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.47+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.3.0+bcdd12964f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.27+ee30b13a4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.42+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.40+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.1+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.10+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.6+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.66+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.9+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.8+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.9+6abb6a4b4f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.1.0+dba1195c4f
			fabric-particles-v1: Fabric Particles (v1) 1.1.8+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.22+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.21+ee30b13a4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.5+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.6+d331d3144f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.54+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.43+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.57+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.1+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.15+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.21+ee30b13a4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.18+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.57+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.18+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.12+90f2d7b14f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.15+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		geckolib: GeckoLib 4 4.4.4
			com_eliotlash_mclib_mclib: mclib 20
		geophilic: Geophilic 3.1.4
		hybrid-aquatic: Hybrid Aquatic 1.3.2
		ichunutil: iChunUtil 1.0.0
		iris: Iris 1.7.2+mc1.20.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 17.3.1.5
		justplayerheads: Just Player Heads 4.0
		lithium: Lithium 0.12.1
		minecraft: Minecraft 1.20.4
		modflared: Modflared 1.2.0+release.60
		notenoughcrashes: Not Enough Crashes 4.4.7+1.20.4
		origins: Origins 1.13.0-alpha.4+mc.1.20.4
			apoli: Apoli 2.12.0-alpha.6+mc.1.20.4
				additionalentityattributes: Additional Entity Attributes 1.7.1+1.20.4
				calio: Calio 1.14.0-alpha.2+mc.1.20.4
					org_quiltmc_parsers_gson: gson 0.2.1
					org_quiltmc_parsers_json: json 0.2.1
				cardinal-components-base: Cardinal Components API (base) 5.4.0
				cardinal-components-entity: Cardinal Components API (entities) 5.4.0
				playerabilitylib: Pal 1.9.0
			reach-entity-attributes: Reach Entity Attributes 2.5.0
		pehkui: Pehkui 3.8.3+1.14.4-1.21
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		plantsjunk: Plants&Junk 1.0.1-1.20.4
			terraform-wood-api-v1: Terraform Wood API (v1) 9.0.0
		replaymod: Replay Mod 1.20.4-2.6.20
		replymod: ReplyMod 1.3.1+1.20.2
		signed_paintings: Signed Paintings 1.1.0-mc1.20.4
		sodium: Sodium 0.5.8+mc1.20.4
		tectonic: Tectonic 2.3.5b
		vcinteraction: Voice Chat Interaction 1.20.4-1.0.5
			polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.7.0+1.20.3-rc1
		voicechat: Simple Voice Chat 1.20.4-2.5.22
		xaeroworldmap: Xaero's World Map 1.39.0
	Loaded Shaderpack: (off)
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Fabric Screen API (v1) (fabric-screen-api-v1)

**Comment by Nettakrim** [comment]
huh that looks like a different and also weirder error

**Comment by r1sk01** [comment]
> huh that looks like a different and also weirder error

thought so as well, but it has the same behaviour as the original issue, it crashes the game sometimes and other times just works and only loads the first frame  
is the mod trying to load all the frames? if so, maybe only attempt to load the first and ignore the rest?
